HA$PBExportHeader$u_tabpg_dwproperty_srvrowselection.sru
$PBExportComments$Extension DataWindow Property - The RowSelection service tabpage
forward
global type u_tabpg_dwproperty_srvrowselection from pfc_u_tabpg_dwproperty_srvrowselection
end type
end forward

global type u_tabpg_dwproperty_srvrowselection from pfc_u_tabpg_dwproperty_srvrowselection
end type
global u_tabpg_dwproperty_srvrowselection u_tabpg_dwproperty_srvrowselection

on u_tabpg_dwproperty_srvrowselection.create
call super::create
end on

on u_tabpg_dwproperty_srvrowselection.destroy
call super::destroy
end on

